name: redux
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Brian Egan <brian@brianegan.com>
description: Redux for Dart
homepage: http://github.com/johnpryan/redux.dart
version: 3.0.1

environment:
  sdk: '>=1.24.0 <3.0.0'

dependencies:
  rxdart: ^0.22.2

dev_dependencies:
  test: '>=0.12.24+2 <2.0.0'
